### ISSUE TITLE
first start hangs with "waiting for database"

### ISSUE THREAD

**Issue by lemmy04** [sdr-enthusiasts/docker-flightairmap#18]
I'm trying to deploy flightairmap in kubernetes with this yaml file:
https://gist.github.com/lemmy04/0e44b82c74b335eca0d7459b67241622

but the first start gets stuck at "waiting for database".
Any ideas?

**Comment by mikenye** [comment]
I'll be pushing a fix for this over the coming days.

**Comment by lemmy04** [comment]
The interesting thing is that if I deploy the same way but in a regular docker it works fine...

**Comment by Freekers** [comment]
I'm experiencing the same issue, but I'm not using Kubernetes. I'm running it as a regular Docker using docker-compose:

```
version: '3.7'

services:

  flightairmap:
    image: mikenye/flightairmap:latest
    tty: true
    container_name: flightairmap
    restart: always
    ports:
      - 8091:80
    environment:
      - TZ=Europe/Amsterdam
      - BASESTATIONHOST=XXXXXXXXX
      - FAM_INSTALLPASSWORD="XXXXXXXXX"
    volumes:
      - /volume1/docker/flightairmap/fam_db:/var/lib/mysql
      - /volume1/docker/flightairmap/fam_webapp:/var/www/flightairmap
```

Log:

```
Creating network "flightairmap_default" with the default driver
Pulling flightairmap (mikenye/flightairmap:latest)...
latest: Pulling from mikenye/flightairmap
cf4624f9a482: Pull complete
a00bc2f295c1: Pull complete
45d143e448d0: Pull complete
Digest: sha256:feb62e95bbe2af182164195b4a5c2c18563c127af6d03715e635e1a24568ca7d
Status: Downloaded newer image for mikenye/flightairmap:latest
Creating flightairmap ... done
Attaching to flightairmap
flightairmap    | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
flightairmap    | [s6-init] ensuring user provided files have correct perms...exited 0.
flightairmap    | [fix-attrs.d] applying ownership & permissions fixes...
flightairmap    | [fix-attrs.d] done.
flightairmap    | [cont-init.d] executing container initialization scripts...
flightairmap    | [cont-init.d] 01-sanitycheck: executing...
flightairmap    | INFO: MYSQLHOSTNAME not set, using local database
flightairmap    | [cont-init.d] 01-sanitycheck: exited 0.
flightairmap    | [cont-init.d] 02-firstrun: executing...
flightairmap    |
flightairmap    | New installation detected. Performing first-run tasks...
flightairmap    | This takes a very long time, please be patient!
flightairmap    |
flightairmap    | Starting temporary services...
flightairmap    | Waiting for database...
```

I've waited for 2 hours, but I don't think anything will happen.
