### ISSUE TITLE
Docker-compose database issues with the examples provided in README.md

### ISSUE THREAD

**Issue by animeai** [sdr-enthusiasts/docker-flightairmap#25]
Both the docker-compose.yml examples in README.md failed to work correctly. The internal database version gave the error "/usr/sbin/mysqld: Please consult the Knowledge Base to find out how to run mysqld as root!", the external database version hung on "Waiting for database" with the errors in the database container "2023-10-27 11:33:15 3 [Warning] Aborted connection 3 to db: 'unconnected' user: 'unauthenticated' host: '172.18.0.14' (This connection closed normally without authentication)"

The fix was simple, change the mariadb provider to linuxserver's which I have always found more user friendly:

```
  flightairmap_db:
    image: lscr.io/linuxserver/mariadb:latest
    tty: true
    container_name: flightairmap_db
    restart: always
    environment:
      - PUID=0
      - PGID=0
      - MYSQL_ROOT_PASSWORD=shai5Eisah7phe0aic5foote
      - MYSQL_DATABASE=flightairmap
      - MYSQL_USER=flightairmap
      - TZ=Europe/London
      - MYSQL_PASSWORD=xi6Paig4yeitae3Pah9aew3j
    volumes:
      - fam_db:/config
```
With this mariadb container it worked with no problem. PUID/PGID could also probably be set as 1000 (or your preferred user/group) but I didn't test this. Note the change in data storage location within the container, and the lack of "command: " for this container.

This was all experienced on a fresh install of ubuntu 22.04 on x64 architecture.
