### ISSUE TITLE
parse error: Invalid numeric literal at line 1, column 5

### ISSUE THREAD

**Issue by Freekers** [sdr-enthusiasts/docker-flightairmap#28]
I've just pulled the latest image and am trying to setup a new instance of flightairmap using an external MariaDB, per the docker-compose in the readme.

Upon starting the stack, I received the following error:

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service libseccomp2: starting
s6-rc: info: service 01-sanitycheck: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service libseccomp2 successfully started
s6-rc: info: service 01-sanitycheck successfully started
s6-rc: info: service 02-firstrun: starting
s6-rc: info: service legacy-cont-init successfully started

Waiting for database...


Database ready.


New installation detected. Performing first-run tasks...

This takes a very long time, please be patient!


Starting temporary services... 

Running install/index.php

parse error: Invalid numeric literal at line 1, column 5

parse error: Invalid numeric literal at line 1, column 5

parse error: Invalid numeric literal at line 1, column 5

parse error: Invalid numeric literal at line 1, column 5

s6-rc: warning: unable to start service 02-firstrun: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service libseccomp2: stopping
s6-rc: info: service 01-sanitycheck: stopping
s6-rc: info: service libseccomp2 successfully stopped
s6-rc: info: service 01-sanitycheck successfully stopped
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

I have no chance to check the /run/uncaught-logs/current folder, because the container immediately exits. I tried mapping /run/uncaught-logs/current to a local folder on my Docker host but then the container refuses to start at all (s6 device busy).

This is my docker-compose file:
```
  flightairmap_db:
    image: lscr.io/linuxserver/mariadb:latest
    tty: true
    container_name: flightairmap_db
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - MYSQL_ROOT_PASSWORD=flightairmap
      - MYSQL_DATABASE=flightairmap
      - MYSQL_USER=flightairmap
      - MYSQL_PASSWORD=flightairmap
    volumes:
      - /opt/docker/flightairmap/db:/config

  flightairmap:
    image: mikenye/flightairmap:latest
    tty: true
    container_name: flightairmap
    restart: unless-stopped
    environment:
      - TZ=Europe/Amsterdam
      - BASESTATIONHOST=192.168.30.224
      - FAM_INSTALLPASSWORD="Test123!"
      - FAM_GLOBALSITENAME=Freekers
      - MYSQLHOSTNAME=flightairmap_db
      - MYSQLDATABASE=flightairmap
      - MYSQLUSERNAME=flightairmap
      - MYSQLPASSWORD=flightairmap
      - MYSQLROOTPASSWORD=flightairmap
    volumes:
      - /opt/docker/flightairmap/webapp:/var/www/flightairmap
    depends_on:
      - flightairmap_db
 ```

I tried removing the TZ, BASESTATIONHOST, FAM_INSTALLPASSWORD, FAM_GLOBALSITENAME environmental variables, but the issue remains.

Thanks
