### ISSUE TITLE
First run - fails

### ISSUE THREAD

**Issue by sledzik1984** [sdr-enthusiasts/docker-flightairmap#30]
Compose file (for Portainer STACK):

```
version: "2.0"

volumes:
  #fam_db:
  fam_webapp:

networks:
  flightairmap:

services:
  #flightairmap_db:
  #  image: lscr.io/linuxserver/mariadb:latest
   # tty: true
    #container_name: flightairmap_db
    #restart: always
    #environment:
    #  - PUID=0
    #  - PGID=0
    #  - MYSQL_ROOT_PASSWORD=shai5Eisah7phe0aic5foote
    #  - MYSQL_DATABASE=flightairmap
    #  - MYSQL_USER=flightairmap
    #  - TZ=${FEEDER_TZ}
    #  - MYSQL_PASSWORD=xi6Paig4yeitae3Pah9aew3j
    #volumes:
    #  - fam_db:/config

  flightairmap:
    image: mikenye/flightairmap:latest
    tty: true
    container_name: flightairmap
    restart: always
    ports:
      - 8005:80
    environment:
      - TZ=Europe/Warsaw
      #- BASESTATIONHOST=192.168.254.183
      - FAM_INSTALLPASSWORD="###"
      - MYSQLHOSTNAME=192.168.15.48
      - MYSQLPORT=3306
      - MYSQLDATABASE=fam
      - MYSQLUSERNAME=fam
      - VERBOSE_LOGGING=false
      - MYSQLPASSWORD=###
      - MYSQLROOTPASSWORD=###
    volumes:
      - fam_webapp:/var/www/flightairmap
    #depends_on:
    #  - flightairmap_db

```

Error (goes in loop):
```
{
  "error": "Unknwon task : ",
  "done": null,
  "next": "finish",
  "install": "finish"
}
+ echo ''
+ echo -e '\033[1;31m"Unknwon task : "\033[0m'
0=U 1=n 2=k 3=n 4=w 5=o 6=n 7=  8=t 9=a 10=s 11=k 12=  13=: 14=  
+ echo ''
+ exit 1
[cont-init.d] 02-firstrun: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
```

Database server works ok (as other services using it work).

**Comment by rikgale** [comment]
Try changing the flightairmap image to 
```
image: ghcr.io/sdr-enthusiasts/docker-flightairmap:latest
```
You appear to be using the old Mike Nye image and some work have been performed on the container since then

**Comment by sledzik1984** [comment]
That's a mistake in bug report. I've tested different images . Actual docker compose I've deployed uses sdr-enthusiasts image:

```
version: "2.0"

volumes:
  #fam_db:
  fam_webapp:

networks:
  flightairmap:

services:
  #flightairmap_db:
  #  image: lscr.io/linuxserver/mariadb:latest
   # tty: true
    #container_name: flightairmap_db
    #restart: always
    #environment:
    #  - PUID=0
    #  - PGID=0
    #  - MYSQL_ROOT_PASSWORD=shai5Eisah7phe0aic5foote
    #  - MYSQL_DATABASE=flightairmap
    #  - MYSQL_USER=flightairmap
    #  - TZ=${FEEDER_TZ}
    #  - MYSQL_PASSWORD=xi6Paig4yeitae3Pah9aew3j
    #volumes:
    #  - fam_db:/config

  flightairmap:
    image: ghcr.io/sdr-enthusiasts/docker-flightairmap:latest
    tty: true
    container_name: flightairmap
    restart: always
    ports:
      - 8005:80
    environment:
      - TZ=Europe/Warsaw
      #- BASESTATIONHOST=192.168.
      - FAM_INSTALLPASSWORD="###"
      - MYSQLHOSTNAME=192.168.15.48
      - MYSQLPORT=3306
      - MYSQLDATABASE=fam
      - MYSQLUSERNAME=fam
      - VERBOSE_LOGGING=false
      - MYSQLPASSWORD=###
      - MYSQLROOTPASSWORD=###
    volumes:
      - fam_webapp:/var/www/flightairmap
    #depends_on:
    #  - flightairmap_db
```

Error remains the same
